#!/usr/bin/env python3
"""
Post-Processing & Analytical Mie Series Validation for 3D PEC Sphere RCS in NekWave.

Reads the Near-to-Far-Field (NTFF) surface integration outputs generated by NekWave:
  - build/output_sphereRCS/rcs_bistatic.csv
  - build/output_sphereRCS/rcs_frequency_sweep.csv
  - build/output_sphereRCS/rcs_surface_history.csv

and compares the simulated E-plane (phi = 0 deg) and H-plane (phi = 90 deg)
bistatic Radar Cross Section (RCS) and broadband backscatter RCS directly
against the exact analytical Mie series solution for a PEC sphere.
"""

import argparse
import math
import os
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ==============================================================================
# Exact Analytical 3D Mie Series for a PEC Sphere (No External Dependencies)
# ==============================================================================

def spherical_jn_yn(n_max, x):
    """
    Computes spherical Bessel functions j_n(x) and y_n(x) for n = 0 .. n_max
    using stable upward recurrence for y_n and Miller's downward recurrence for j_n.
    """
    x = float(x)
    if abs(x) < 1e-14:
        jn = np.zeros(n_max + 1)
        yn = np.full(n_max + 1, -np.inf)
        jn[0] = 1.0
        return jn, yn

    # Upward recurrence for spherical Neumann function y_n(x)
    yn = np.zeros(n_max + 1)
    yn[0] = -math.cos(x) / x
    if n_max >= 1:
        yn[1] = -math.cos(x) / (x * x) - math.sin(x) / x
    for n in range(1, n_max):
        yn[n + 1] = ((2 * n + 1) / x) * yn[n] - yn[n - 1]

    # Downward Miller recurrence for spherical Bessel function j_n(x)
    n_start = n_max + max(25, int(2.0 * x))
    j_down = np.zeros(n_start + 2)
    j_down[n_start + 1] = 0.0
    j_down[n_start] = 1.0
    for n in range(n_start, 0, -1):
        j_down[n - 1] = ((2 * n + 1) / x) * j_down[n] - j_down[n + 1]

    scale = (math.sin(x) / x) / j_down[0]
    jn = j_down[: n_max + 1] * scale
    return jn, yn


def mie_pec_sphere_bistatic(ka, theta_rad):
    """
    Computes the exact normalized bistatic RCS sigma / (pi * a^2) in the
    E-plane (phi = 0 deg) and H-plane (phi = 90 deg) for a PEC sphere of
    electrical size ka = k * a at polar angles theta_rad (0 = forward, pi = back).
    """
    ka = float(ka)
    theta_rad = np.asarray(theta_rad, dtype=float)
    mu = np.cos(theta_rad)

    n_max = max(15, int(ka + 4.0 * (ka ** (1.0 / 3.0)) + 10))
    jn, yn = spherical_jn_yn(n_max, ka)
    hn = jn + 1j * yn

    # Riccati-Bessel functions psi_n(x) = x * j_n(x), xi_n(x) = x * h_n^(1)(x)
    # and their derivatives psi_n'(x) = x * j_{n-1}(x) - n * j_n(x)
    a_n = np.zeros(n_max + 1, dtype=complex)
    b_n = np.zeros(n_max + 1, dtype=complex)

    for n in range(1, n_max + 1):
        psi_n = ka * jn[n]
        xi_n = ka * hn[n]
        dpsi_n = ka * jn[n - 1] - n * jn[n]
        dxi_n = ka * hn[n - 1] - n * hn[n]

        a_n[n] = -dpsi_n / dxi_n
        b_n[n] = -psi_n / xi_n

    # Angular functions pi_n(cos theta) and tau_n(cos theta) via recurrence
    pi_prev2 = np.zeros_like(mu)  # pi_0
    pi_prev1 = np.ones_like(mu)   # pi_1

    S1 = np.zeros_like(mu, dtype=complex)  # H-plane amplitude (phi = 90 deg)
    S2 = np.zeros_like(mu, dtype=complex)  # E-plane amplitude (phi = 0 deg)

    for n in range(1, n_max + 1):
        if n == 1:
            pi_n = pi_prev1
        else:
            pi_n = ((2 * n - 1) / (n - 1)) * mu * pi_prev1 - (n / (n - 1)) * pi_prev2
            pi_prev2 = pi_prev1
            pi_prev1 = pi_n

        tau_n = n * mu * pi_n - (n + 1) * pi_prev2 if n > 1 else mu

        weight = (2.0 * n + 1.0) / (n * (n + 1.0))
        S1 += weight * (a_n[n] * pi_n + b_n[n] * tau_n)
        S2 += weight * (a_n[n] * tau_n + b_n[n] * pi_n)

    rcs_e_norm = (4.0 / (ka * ka)) * (np.abs(S2) ** 2)
    rcs_h_norm = (4.0 / (ka * ka)) * (np.abs(S1) ** 2)
    return rcs_e_norm, rcs_h_norm


def mie_pec_sphere_backscatter(ka_array):
    """
    Computes exact monostatic backscatter RCS sigma(180 deg) / (pi * a^2)
    and forward scatter RCS sigma(0 deg) / (pi * a^2) across an array of ka values.
    """
    ka_array = np.asarray(ka_array, dtype=float)
    back_norm = np.zeros_like(ka_array)
    fwd_norm = np.zeros_like(ka_array)

    for idx, ka in enumerate(ka_array):
        e_norm, _ = mie_pec_sphere_bistatic(ka, np.array([0.0, math.pi]))
        fwd_norm[idx] = e_norm[0]
        back_norm[idx] = e_norm[1]

    return back_norm, fwd_norm


# ==============================================================================
# Main Plotting Routine
# ==============================================================================

def main():
    parser = argparse.ArgumentParser(description="Plot NekWave 3D PEC Sphere RCS vs. Analytical Mie Series")
    parser.add_argument("--dir", type=str, default="build/output_sphereRCS",
                        help="Path to NekWave sphereRCS output directory")
    parser.add_argument("--radius", type=float, default=0.30,
                        help="PEC sphere radius a in meters (default: 0.30)")
    parser.add_argument("--wavelength", type=float, default=0.30,
                        help="Incident carrier wavelength lambda0 in meters (default: 0.30)")
    args = parser.parse_args()

    out_dir = args.dir
    bistatic_csv = os.path.join(out_dir, "rcs_bistatic.csv")
    freq_csv = os.path.join(out_dir, "rcs_frequency_sweep.csv")
    hist_csv = os.path.join(out_dir, "rcs_surface_history.csv")

    if not os.path.exists(bistatic_csv):
        print(f"Error: Could not find {bistatic_csv}. Run the sphereRCS simulation first.")
        sys.exit(1)

    a = args.radius
    k0 = 2.0 * math.pi / args.wavelength
    ka0 = k0 * a
    geom_area = math.pi * a * a

    # Load bistatic RCS CSV
    bistatic_data = np.genfromtxt(bistatic_csv, delimiter=",", names=True)
    theta_deg = bistatic_data["theta_deg"]
    theta_rad = bistatic_data["theta_rad"]
    nek_e_norm = bistatic_data["rcs_e_plane_norm"]
    nek_h_norm = bistatic_data["rcs_h_plane_norm"]

    # Compute exact analytical Mie series at the same angles
    mie_e_norm, mie_h_norm = mie_pec_sphere_bistatic(ka0, theta_rad)

    nek_e_db = 10.0 * np.log10(np.maximum(nek_e_norm, 1e-12))
    nek_h_db = 10.0 * np.log10(np.maximum(nek_h_norm, 1e-12))
    mie_e_db = 10.0 * np.log10(np.maximum(mie_e_norm, 1e-12))
    mie_h_db = 10.0 * np.log10(np.maximum(mie_h_norm, 1e-12))

    # Create 2x2 diagnostic figure
    fig = plt.figure(figsize=(14, 10), dpi=180)
    fig.suptitle(
        f"3D RCS PEC Sphere ($a = {a:.2f}$ m, $k_0 a = {ka0:.2f}$) with NekWave ($p=6$)",
        fontsize=14, fontweight="bold", y=0.98
    )

    # --------------------------------------------------------------------------
    # Panel 1: Bistatic RCS (Normalized dB) vs. Scattering Angle theta
    # --------------------------------------------------------------------------
    ax1 = fig.add_subplot(2, 2, 1)
    ax1.plot(theta_deg, mie_e_db, "k-", lw=2.0, label="Exact Mie Series (E-plane, $\\phi=0^\\circ$)")
    ax1.plot(theta_deg, mie_h_db, "k--", lw=1.8, label="Exact Mie Series (H-plane, $\\phi=90^\\circ$)")
    ax1.plot(theta_deg, nek_e_db, "r-", lw=1.8, alpha=0.9, label="NekWave NTFF (E-plane, $\\phi=0^\\circ$)")
    ax1.plot(theta_deg, nek_h_db, "b-.", lw=1.8, alpha=0.9, label="NekWave NTFF (H-plane, $\\phi=90^\\circ$)")
    ax1.set_xlim(0.0, 180.0)
    ax1.set_xticks(np.arange(0, 181, 30))
    ax1.set_xlabel("Bistatic Scattering Angle $\\theta_s$ [deg] ($0^\\circ$ = Forward, $180^\\circ$ = Backscatter)")
    ax1.set_ylabel("Normalized Bistatic RCS $10\\log_{10}(\\sigma / \\pi a^2)$ [dB]")
    ax1.set_title(f"(a) Bistatic RCS")
    ax1.grid(True, linestyle=":", alpha=0.6)
    ax1.legend(loc="upper right", fontsize=8.5)

    # --------------------------------------------------------------------------
    # Panel 2: Polar Radiation Pattern (E-plane & H-plane)
    # --------------------------------------------------------------------------
    ax2 = fig.add_subplot(2, 2, 2, projection="polar")
    theta_full = np.concatenate([theta_rad, 2.0 * math.pi - theta_rad[::-1]])
    mie_e_full = np.concatenate([mie_e_db, mie_e_db[::-1]])
    nek_e_full = np.concatenate([nek_e_db, nek_e_db[::-1]])
    mie_h_full = np.concatenate([mie_h_db, mie_h_db[::-1]])
    nek_h_full = np.concatenate([nek_h_db, nek_h_db[::-1]])

    db_floor = -20.0
    ax2.plot(theta_full, np.maximum(mie_e_full, db_floor), "k-", lw=1.8, label="Mie E-plane")
    ax2.plot(theta_full, np.maximum(nek_e_full, db_floor), "r--", lw=1.8, label="NekWave E-plane")
    ax2.plot(theta_full, np.maximum(mie_h_full, db_floor), "b:", lw=1.8, label="NekWave H-plane")
    ax2.set_ylim(db_floor, max(20.0, float(np.max(mie_e_db)) + 3.0))
    ax2.set_title("(b) Polar Bistatic RCS [dB($\\sigma / \\pi a^2$)]", pad=15)
    ax2.legend(loc="upper right", bbox_to_anchor=(1.25, 1.12), fontsize=8.5)

    # --------------------------------------------------------------------------
    # Panel 3: Broadband Monostatic Backscatter RCS vs. Electrical Size (ka)
    # --------------------------------------------------------------------------
    ax3 = fig.add_subplot(2, 2, 3)
    ka_fine = np.linspace(0.3, 12.0, 400)
    mie_back_fine, _ = mie_pec_sphere_backscatter(ka_fine)
    ax3.plot(ka_fine, mie_back_fine, "k-", lw=2.0, label="Exact Mie Backscatter $\\sigma(180^\\circ)/(\\pi a^2)$")
    ax3.axhline(1.0, color="gray", linestyle="--", lw=1.0, label="Optical Limit ($\\sigma = \\pi a^2$)")

    if os.path.exists(freq_csv):
        freq_data = np.genfromtxt(freq_csv, delimiter=",", names=True)
        # Skip row 0 (duplicate of k0) and filter where incident pulse spectrum has sufficient SNR
        ka_sweep = freq_data["ka"][1:]
        einc_mag = freq_data["Einc_mag"][1:]
        back_sweep = freq_data["backscatter_rcs_norm"][1:]
        valid = einc_mag >= 0.15 * np.max(einc_mag)
        ax3.plot(ka_sweep[valid], back_sweep[valid], "ro-", ms=3.5, lw=1.4,
                 label="NekWave Broadband Pulse DFT")

    ax3.plot([ka0], [nek_e_norm[-1]], "bs", ms=7, label=f"Carrier $k_0 a = {ka0:.2f}$")
    ax3.set_xlim(0.3, 12.0)
    ax3.set_ylim(0.0, 4.2)
    ax3.set_xlabel("Electrical Size $k a = 2\\pi a / \\lambda$")
    ax3.set_ylabel("Normalized Monostatic RCS $\\sigma(180^\\circ) / (\\pi a^2)$")
    ax3.set_title("(c) Monostatic RCS")
    ax3.grid(True, linestyle=":", alpha=0.6)
    ax3.legend(loc="upper right", fontsize=8.5)

    # --------------------------------------------------------------------------
    # Panel 4: Time-Domain Surface Current History on PEC Sphere
    # --------------------------------------------------------------------------
    ax4 = fig.add_subplot(2, 2, 4)
    if os.path.exists(hist_csv):
        hist_data = np.genfromtxt(hist_csv, delimiter=",", names=True)
        ax4.plot(hist_data["time"], hist_data["Einc_origin"], "k--", lw=1.4, alpha=0.75,
                 label="Incident Wave $E_z^{\\mathrm{inc}}(\\mathbf{0}, t)$")
        ax4.plot(hist_data["time"], hist_data["rms_Js"], "r-", lw=1.8,
                 label="Induced Surface Current $\\|\\mathbf{J}_s\\|_{\\mathrm{RMS}}(t)$")
        ax4.plot(hist_data["time"], hist_data["rms_Ms"], "b:", lw=1.5,
                 label="Weak DG Trace $\\|\\mathbf{M}_s\\|_{\\mathrm{RMS}}(t)$")
        ax4.set_xlabel("Simulation Time $t$ [s ($c=1$)]")
        ax4.set_ylabel("Field / Surface Current Amplitude")
        ax4.set_title("(d) Surface Currents")
        ax4.grid(True, linestyle=":", alpha=0.6)
        ax4.legend(loc="upper right", fontsize=8.5)

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    png_path = os.path.join(out_dir, "sphere_rcs_comparison.png")
    pdf_path = os.path.join(out_dir, "sphere_rcs_comparison.pdf")
    plt.savefig(png_path, dpi=200)
    plt.savefig(pdf_path)
    print(f"[PLOT] Saved RCS comparison plots to:\n  - {png_path}\n  - {pdf_path}")


if __name__ == "__main__":
    main()
