// ==============================================================================
// NekWave Example: 3D PEC Sphere Scattering (RCS) in Vacuum with UPML Boundaries
// ==============================================================================
//
// Geometry (generated by meshing/sphereRCS/spherePEC.py & gmsh2nek.py):
//   - Hollow PEC sphere of radius r_sphere = 0.3 m centered at (0, 0, 0)
//   - Inner vacuum cubed-sphere region extending to [-1.75, +1.75]^3 m
//   - Concentric 5-layer hexahedral UPML absorbing shell on [-2.0, +2.0]^3 m
//
// Incident Wave Initialization (Traveling Planar Wave Packet in +x):
//   - Launches a Gaussian-modulated TEM_x planar wave packet from x0 = -1.05 m
//     traveling in the +x direction (c = 1) toward the PEC sphere:
//       Ez(x, y, z, 0) = E0 * cos(k0 * (x - x0)) * exp(-(x - x0)^2 / (2 * sigma_x^2)) * W(y, z)
//       Hy(x, y, z, 0) = -Ez(x, y, z, 0)
//     where Poynting vector S = E x H = (-Ez * Hy) x_hat = +|Ez|^2 x_hat points in +x.
//   - W(y, z) is a flat-top 8th-order super-Gaussian transverse window that is
//     uniformly 1.0 across the entire PEC sphere (|y|, |z| <= 0.3 m) while
//     tapering smoothly to zero before the lateral PML layers (|y|, |z| >= 1.75 m).
// ==============================================================================

#include "case.hpp"
#include "comm.hpp"
#include <iostream>
#include <cmath>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

int main(int argc, char* argv[]) {
    Comm::init(&argc, &argv);

    if (Comm::isRoot()) {
        std::cout << "==========================================================" << std::endl;
        std::cout << "   NekWave Simulation: 3D PEC Sphere Scattering (UPML)    " << std::endl;
        std::cout << "==========================================================" << std::endl;
    }

    std::string configFile = "examples/sphereRCS/sphereRCS.json";
    if (argc > 1) {
        configFile = argv[1];
    }

    Case simulationCase;
    simulationCase.loadConfig(configFile);
    simulationCase.setWaveType("sphereRCS");

    // --------------------------------------------------------------------------
    // Traveling Planar Wave Packet Initial Condition (+x propagation)
    // --------------------------------------------------------------------------
    simulationCase.setInitialConditionHook([](double x, double y, double z,
                                              double& ex, double& ey, double& ez,
                                              double& hx, double& hy, double& hz) {
        // Wave packet parameters (upstream of the r = 0.3 m PEC sphere, inside [-1.5, 1.5]^3 vacuum)
        const double E0      = 1.0;                 // Peak electric field amplitude
        const double x0      = -0.90;               // Initial pulse center along x (m)
        const double sigmaX  = 0.14;                // Longitudinal Gaussian pulse width (m)
        const double lambda0 = 0.30;                // Carrier wavelength (m) -> k0 * r_sphere = 2*pi
        const double k0      = 2.0 * M_PI / lambda0;
        const double wPerp   = 1.05;                // Flat-top transverse window half-width (m)

        // Longitudinal Gaussian-modulated carrier wave along x
        double dx = x - x0;
        double envX = std::exp(-(dx * dx) / (2.0 * sigmaX * sigmaX));
        double carrier = std::cos(k0 * dx);

        // Flat-top super-Gaussian transverse window W(y, z):
        // W(y, z) ~ 1.0 across the sphere (|y|, |z| <= 0.3) and vanishes inside lateral PMLs
        double ry2 = (y / wPerp) * (y / wPerp);
        double rz2 = (z / wPerp) * (z / wPerp);
        double ry8 = ry2 * ry2 * ry2 * ry2;
        double rz8 = rz2 * rz2 * rz2 * rz2;
        double windowYZ = std::exp(-(ry8 + rz8));

        double pulse = E0 * carrier * envX * windowYZ;

        // TEM_x polarization: E = (0, 0, Ez), H = (0, Hy, 0) with Hy = -Ez for +x propagation
        ex = 0.0;
        ey = 0.0;
        ez = pulse;

        hx = 0.0;
        hy = -pulse;
        hz = 0.0;
    });

    // --------------------------------------------------------------------------
    // Configure Field Exports (HDF5 + XDMF for ParaView visualization)
    // --------------------------------------------------------------------------
    Case::SaveOptions saveOptions;
    saveOptions.saveE = true;
    saveOptions.saveH = true;
    saveOptions.saveCurlE = false;
    saveOptions.saveCurlH = false;
    saveOptions.saveDivE = false;
    saveOptions.saveDivH = false;
    saveOptions.saveMagnitudeE = true;
    saveOptions.saveMagnitudeH = true;
    saveOptions.saveMagnitudeCurlE = false;
    saveOptions.saveMagnitudeCurlH = false;
    saveOptions.saveEnergyDensity = true;
    simulationCase.setSaveOptions(saveOptions);

    // --------------------------------------------------------------------------
    // Execute 3-Phase Simulation Lifecycle
    // --------------------------------------------------------------------------
    simulationCase.preprocess();
    simulationCase.simulate();
    simulationCase.postprocess();

    if (Comm::isRoot()) {
        std::cout << "Sphere RCS scattering simulation completed successfully.\n" << std::endl;
    }

    Comm::finalize();
    return 0;
}
