// ==============================================================================
// NekWave Example: 3D PEC Sphere Scattering (RCS) in Vacuum with UPML Boundaries
// ==============================================================================
//
// Geometry (generated by meshing/sphereRCS/spherePEC.py & gmsh2nek.py):
//   - Hollow PEC sphere of radius r_sphere = 0.3 m centered at (0, 0, 0)
//   - Inner vacuum cubed-sphere region extending to [-1.75, +1.75]^3 m
//   - Concentric 5-layer hexahedral UPML absorbing shell on [-2.0, +2.0]^3 m
//
// Incident Wave Initialization (Traveling Planar Wave Packet in +x):
//   - Launches a Gaussian-modulated TEM_x planar wave packet from x0 = -1.05 m
//     traveling in the +x direction (c = 1) toward the PEC sphere:
//       Ez(x, y, z, 0) = E0 * cos(k0 * (x - x0)) * exp(-(x - x0)^2 / (2 * sigma_x^2)) * W(y, z)
//       Hy(x, y, z, 0) = -Ez(x, y, z, 0)
//     where Poynting vector S = E x H = (-Ez * Hy) x_hat = +|Ez|^2 x_hat points in +x.
//   - W(y, z) is a flat-top 8th-order super-Gaussian transverse window that is
//     uniformly 1.0 across the entire PEC sphere (|y|, |z| <= 0.3 m) while
//     tapering smoothly to zero before the lateral PML layers (|y|, |z| >= 1.75 m).
// ==============================================================================

#include "case.hpp"
#include "comm.hpp"
#include <iostream>
#include <cmath>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

int main(int argc, char* argv[]) {
    Comm::init(&argc, &argv);

    if (Comm::isRoot()) {
        std::cout << "==========================================================" << std::endl;
        std::cout << "   NekWave Simulation: 3D PEC Sphere Scattering (UPML)    " << std::endl;
        std::cout << "==========================================================" << std::endl;
    }

    std::string configFile = "examples/sphereRCS/sphereRCS.json";
    if (argc > 1) {
        configFile = argv[1];
    }

    Case simulationCase;
    simulationCase.loadConfig(configFile);
    simulationCase.setWaveType("sphereRCS");

    // --------------------------------------------------------------------------
    // Traveling Planar Wave Packet Parameters (+x propagation, +z polarization)
    // --------------------------------------------------------------------------
    const double rSphere = 0.30;                // PEC sphere radius (m)
    const double E0      = 1.0;                 // Peak electric field amplitude
    const double x0      = -0.90;               // Initial pulse center along x (m)
    const double sigmaX  = 0.14;                // Longitudinal Gaussian pulse width (m)
    const double lambda0 = 0.30;                // Carrier wavelength (m) -> k0 * r_sphere = 2*pi
    const double k0      = 2.0 * M_PI / lambda0;
    const double wPerp   = 1.05;                // Flat-top transverse window half-width (m)

    const bool scatteredMode = simulationCase.config().scatteredFieldMode;

    if (!scatteredMode) {
        // Total-Field Mode: Initialize windowed traveling wave packet in volume at t = 0
        simulationCase.setInitialConditionHook([=](double x, double y, double z,
                                                   double& ex, double& ey, double& ez,
                                                   double& hx, double& hy, double& hz) {
            // Longitudinal Gaussian-modulated carrier wave along x
            double dx = x - x0;
            double envX = std::exp(-(dx * dx) / (2.0 * sigmaX * sigmaX));
            double carrier = std::cos(k0 * dx);

            // Flat-top super-Gaussian transverse window W(y, z):
            // W(y, z) ~ 1.0 across the sphere (|y|, |z| <= 0.3) and vanishes inside lateral PMLs
            double ry2 = (y / wPerp) * (y / wPerp);
            double rz2 = (z / wPerp) * (z / wPerp);
            double ry8 = ry2 * ry2 * ry2 * ry2;
            double rz8 = rz2 * rz2 * rz2 * rz2;
            double windowYZ = std::exp(-(ry8 + rz8));

            double pulse = E0 * carrier * envX * windowYZ;

            // TEM_x polarization: E = (0, 0, Ez), H = (0, Hy, 0) with Hy = -Ez for +x propagation
            ex = 0.0;
            ey = 0.0;
            ez = pulse;

            hx = 0.0;
            hy = -pulse;
            hz = 0.0;
        });
    } else if (Comm::isRoot()) {
        std::cout << "[SETUP] Scattered-Field Mode active: volume initialized to E_scat = H_scat = 0;\n"
                  << "        analytical 1D plane wave applied on PEC sphere and summed back on export." << std::endl;
    }

    // --------------------------------------------------------------------------
    // Configure Near-to-Far-Field (NTFF) & Bistatic RCS Monitor on PEC Surface
    // --------------------------------------------------------------------------
    RcsConfig rcsCfg;
    rcsCfg.enabled = true;
    rcsCfg.sphereRadius = rSphere;
    rcsCfg.numTheta = 361; // 0.5-degree angular resolution from 0 to 180 deg
    rcsCfg.kHatInc = {{1.0, 0.0, 0.0}}; // +x incident wave propagation
    rcsCfg.eHatInc = {{0.0, 0.0, 1.0}}; // +z electric field polarization

    // Configure analytical incident plane wave for Scattered-Field PEC excitation & total-field save
    rcsCfg.incidentPlaneWave.enabled      = scatteredMode;
    rcsCfg.incidentPlaneWave.E0           = E0;
    rcsCfg.incidentPlaneWave.k0           = k0;
    rcsCfg.incidentPlaneWave.x0           = x0;
    rcsCfg.incidentPlaneWave.sigmaX       = sigmaX;
    rcsCfg.incidentPlaneWave.sphereRadius = rSphere;
    rcsCfg.incidentPlaneWave.kx           = 1.0;
    rcsCfg.incidentPlaneWave.ky           = 0.0;
    rcsCfg.incidentPlaneWave.kz           = 0.0;
    rcsCfg.incidentPlaneWave.ex           = 0.0;
    rcsCfg.incidentPlaneWave.ey           = 0.0;
    rcsCfg.incidentPlaneWave.ez           = 1.0;
    rcsCfg.incidentPlaneWave.updateMagneticPolarization();

    // Primary carrier wavenumber k0 first, followed by broadband sweep over ka in [0.5, 9.0]
    rcsCfg.wavenumbers.push_back(k0);
    const int numSweepFreqs = 85;
    for (int m = 0; m <= numSweepFreqs; ++m) {
        double ka = 0.5 + (8.5 * m) / static_cast<double>(numSweepFreqs);
        rcsCfg.wavenumbers.push_back(ka / rSphere);
    }

    // Incident wave time waveform E_z^{inc}(0, t) at the sphere center r = (0, 0, 0)
    rcsCfg.incidentWaveFn = [=](double t) {
        double phaseX = -x0 - t; // x - x0 - c*t evaluated at x = 0, c = 1
        return E0 * std::cos(k0 * phaseX) * std::exp(-(phaseX * phaseX) / (2.0 * sigmaX * sigmaX));
    };
    simulationCase.setRcsConfig(rcsCfg);

    // --------------------------------------------------------------------------
    // Configure Field Exports (HDF5 + XDMF for ParaView visualization)
    // --------------------------------------------------------------------------
    Case::SaveOptions saveOptions;
    saveOptions.saveE = true;
    saveOptions.saveH = true;
    saveOptions.saveCurlE = false;
    saveOptions.saveCurlH = false;
    saveOptions.saveDivE = false;
    saveOptions.saveDivH = false;
    saveOptions.saveMagnitudeE = false;
    saveOptions.saveMagnitudeH = false;
    saveOptions.saveMagnitudeCurlE = false;
    saveOptions.saveMagnitudeCurlH = false;
    saveOptions.saveEnergyDensity = true;
    simulationCase.setSaveOptions(saveOptions);

    // --------------------------------------------------------------------------
    // Execute 3-Phase Simulation Lifecycle
    // --------------------------------------------------------------------------
    simulationCase.preprocess();
    simulationCase.simulate();
    simulationCase.postprocess();

    if (Comm::isRoot()) {
        std::cout << "Sphere RCS scattering simulation completed successfully.\n" << std::endl;
    }

    Comm::finalize();
    return 0;
}
